### ISSUE TITLE
Something wrong in the evaluation code.

### ISSUE THREAD

**Issue by weleen** [jackie840129/STE-NVAN#1]
The implementation in cmc.py is different from the other open source code. 
And I try to remove the query_idx from g_idx, then the cmc and mAP drops.

[cmc.py](https://github.com/jackie840129/STE-NVAN/blob/4805c74afe44cbd53dd66b12763c5a2db9ab4a34/util/cmc.py#L19)

**Comment by AsuradaYuci** [comment]
I think we should use the official evaluation code, or it's unfair to compare.

**Comment by jackie840129** [comment]
Hi  @AsuradaYuci and @weleen ~ 
I think in MARS evaluation script, the query images are also in gallery images.
https://github.com/liangzheng06/MARS-evaluation/blob/master/test_mars.m
In this code, line 26~36, they pick the query idx from gallery. But they didn't delete it from the gallery.

Or did I misunderstand something in their code?

**Comment by AsuradaYuci** [comment]
@weleen emmm, the sampler method of test dataset is also unusual. When I test on the Mars, I can only set the batchsize=1,and it takes about 30 mins to eval. This version eval code is really fast...

**Comment by jackie840129** [comment]
Hi @AsuradaYuci ,
We can adjust the batch size in the test dataloader.
My method for the images sampled from a track in testing followed this paper:
https://zpascal.net/cvpr2018/Li_Diversity_Regularized_Spatiotemporal_CVPR_2018_paper.pdf

ps. In my computer, if I set batch size = 32 for testing, I can run it within 2 mins.

**Comment by AsuradaYuci** [comment]
@jackie840129 Thanks for your reply, I will read the papers more carefully. :smile:

**Comment by jackie840129** [comment]
Thanks for your discussions!
I will carefully check my evaluation methods be as same as MARS and DukeVideo, and update some details in my codes in Readme files as soon as possible.

**Comment by weleen** [comment]
@jackie840129 Thank you for your reply. And I find that I made a mistake by using the evaluation code for market1501.

**Comment by jingwenyangwz** [comment]
In one of the issues in the MARS_Evaluation repo, they figured out that at the end the query data is added into junk and will not be included when calculating mAP and CMC. Can you please double-check? Here is the issue link: 
https://github.com/liangzheng06/MARS-evaluation/issues/4#issuecomment-469798474

Thanks. 


Hey, I realized here you did the same as the original author. Remove the sequences in the gallery set that have the same userID and camID.    https://github.com/jackie840129/STE-NVAN/blob/2091351dec15d1ce48664d81fe658a278f5903a3/util/cmc.py#L43
So no more question. :)

> Hi @AsuradaYuci and @weleen ~
> I think in MARS evaluation script, the query images are also in gallery images.
> https://github.com/liangzheng06/MARS-evaluation/blob/master/test_mars.m
> In this code, line 26~36, they pick the query idx from gallery. But they didn't delete it from the gallery.
> 
> Or did I misunderstand something in their code?
