### ISSUE TITLE
training on Two GPUs, get the results cmc=87.5, map=33.1. ???

### ISSUE THREAD

**Issue by ccq195** [jackie840129/STE-NVAN#10]
Hi, thanks for your code. But when i train the baseline by myself, on two GPUs, class_per_bacth(16), track_per_class(3), S(6), other parameters same with you paper,. We get the results cmc=87.5, map=33.1. I can not understand why the mAP is so low. Looking forward your replay, Thanks.

**Comment by chenchenver** [comment]
你好，请问您在对MARS数据集训练代码的时候存不存在exit(-1)异常退出的问题呢。

**Comment by Kewenjing1020** [comment]
@ccq195 I trained baseline on two GPUs, i get the result: R1=88.54, mAP=80.71%. 
@chenchenver delete exit(-1) in train_NL.py
