### ISSUE TITLE
runtimeerror:Expected object of scalar type Bool but got scalar type Byte for argument #2 'other' in call to _th_xor

### ISSUE THREAD

**Issue by tonyzhumc** [jackie840129/STE-NVAN#11]
When run to the  follow codes:
######
if mode == 'id':
     if id is None:
                 raise RuntimeError('foward is in id mode, please input id!')
            else:
                 identity_mask = torch.eye(feat.size(0)).byte()
                 identity_mask = identity_mask.cuda() if id.is_cuda else identity_mask
                 same_id_mask = torch.eq(id.unsqueeze(1), id.unsqueeze(0))
                 negative_mask = same_id_mask ^ 1
                 positive_mask = same_id_mask ^ identity_mask
######
then this error appear:Expected object of scalar type Bool but got scalar type Byte for argument #2 'other' in call to _th_xor

**Comment by jackie840129** [comment]
I think it is caused by the pytorch version.
You can change the .byte() to .bool().

**Comment by tonyzhumc** [comment]
Thanks for your answer，I haved running the code successfully by your recommend.
