### ISSUE TITLE
Why choose non_layers=[0, 2, 3, 0] and stripes=[16, 16, 16, 16] as your baseline implementation?

### ISSUE THREAD

**Issue by GewelsJI** [jackie840129/STE-NVAN#15]
Looking forward your reply! Thanks!

**Comment by jackie840129** [comment]
Hi @GewelsJI 
In my baseline (NVAN), I choose [0,2,3,0] because I follow the 5-non-local setting in the original paper.
I didn't use stripe in my baseline and it is only adopted in my STE-NVAN.
Thanks

**Comment by GewelsJI** [comment]
Thanks your replying, do you further investigate the different setting of `non_layers`?

**Comment by jackie840129** [comment]
I've tried different number of non-layers in Table 3 of my paper.
