### ISSUE TITLE
DukeMTMC-videoReID dataset preprocess

### ISSUE THREAD

**Issue by nerddd** [jackie840129/STE-NVAN#16]
In create_DukeV_database.py line 64-67
```
        for track in tracks:
            if [id,track] == query_info[0]:
                track_idx.append(idx)
                del query_info[0]
```
I'm comfused about the operation...

**Comment by jackie840129** [comment]
Hi @nerddd 
Because the query data is duplicated in the gallery data. We don't really need to load images in query directory, just record the idx in gallery set.
The "del" operation is just like the pop-out operation to the list~
