### ISSUE TITLE
the problem is here

### ISSUE THREAD

**Issue by SaintyLiu** [jackie840129/STE-NVAN#17]
Start dataloader...
End dataloader...

Epoch 0
  0%|                                                                        | 0/78 [00:00<?, ?it/s]Traceback (most recent call last):
  File "train_baseline.py", line 148, in <module>
    trip_loss = criterion_triplet(pool_feat,labels,dis_func='eu')
  File "/home/lq/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lq/code/person-ReID/STE-NVAN/util/loss.py", line 32, in forward
    negative_mask = same_id_mask ^ 1
RuntimeError: result type Long can't be cast to the desired output type Bool

pytorch 1.5
cuda 10.0

**Comment by jackie840129** [comment]
You can change the "1" to "True"
because the new pytorch version makes the type of "same_id_mask" tensor be a bool tensor.

**Comment by SaintyLiu** [comment]
thank you！I will try it




            
            
                
                    
                            
                                
                            
                            
                                541491286
                            
                    
                        
                            
                                    邮箱：541491286@qq.com
                            
                        
                
            
        Signature is customized by Netease Mail Master


On 05/11/2020 16:47, Chih-Ting Liu (劉致廷) wrote: 
You can change the "1" to "True"
because the new pytorch version makes the type of "same_id_mask" tensor be a bool tensor.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/jackie840129/STE-NVAN/issues/17#issuecomment-626563446",
"url": "https://github.com/jackie840129/STE-NVAN/issues/17#issuecomment-626563446",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by SaintyLiu** [comment]
Start dataloader...
End dataloader...
Inference: 100%|██████████████████████████████████████████████████| 130/130 [00:50<00:00,  2.59it/s]
Traceback (most recent call last):
  File "evaluate.py", line 86, in <module>
    cmc, map = validation(network, test_dataloader, args)
  File "evaluate.py", line 58, in validation
    gallery_cams, dataloader.dataset.query_idx, 10000)
  File "/home/lq/code/person-ReID/STE-NVAN/util/cmc.py", line 20, in Video_Cmc
    q_data = {k:v[q_idx] for k, v in data.items()}
  File "/home/lq/code/person-ReID/STE-NVAN/util/cmc.py", line 20, in <dictcomp>
    q_data = {k:v[q_idx] for k, v in data.items()}
IndexError: index 8298 is out of bounds for axis 0 with size 8298
run_evaluate.sh: 12: run_evaluate.sh: --batch_size: not found

I have another problem.
