### ISSUE TITLE
Evaluate on Duke-Video datasets

### ISSUE THREAD

**Issue by Nasturtium-yyc** [jackie840129/STE-NVAN#19]
i use this code to train model on Duke-video dataset,then i change the path in run_evaluate.sh and run it ,but it has something wrong.
Traceback (most recent call last):
  File "evaluate.py", line 77, in <module>
    network.load_state_dict(state,strict=True)
  File "/home/cczulab515/anaconda3/envs/py37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 769, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for DataParallel:
        size mismatch for module.classifier.weight: copying a param with shape torch.Size([702, 2048]) from checkpoint, the shape in current model is torch.Size([625, 2048]).

Then i chang the line,  **network.load_state_dict(state,strict=False)**,but this problem still exits。Please tell me why. THANK YOU!

**Comment by jackie840129** [comment]
This is because the number of ID is mismatch.
You can either remove the classifier weight in your state_dice or create the model with the same number of ID.

**Comment by Nasturtium-yyc** [comment]
Thank you for your instruction.i will try it again.
