### ISSUE TITLE
Counfusion with position of non-local block

### ISSUE THREAD

**Issue by Woolseyyy** [jackie840129/STE-NVAN#7]
Hi, Thank you for your wonderful job!
I am studying non local block aiming to apply this on another network and your work is a good inspiration. However, I found the position of non-local block in your [ResNet_Video_nonlocal](https://github.com/jackie840129/STE-NVAN/blob/master/net/resnet.py#L224) is different from the original paper and its repos( [repo1](https://github.com/AlexHex7/Non-local_pytorch) & [repo2](https://github.com/facebookresearch/video-nonlocal-net) ).
They put the non-local block in front of residual block, contrary to you. I consider non-local as a module to connect pixels in order to expand the receptive field of convolution layer, so I think it affect the convolution layer behind it.
What's your opinon about its position and why it work?
Looking forward to your reply!

**Comment by jackie840129** [comment]
Because the original paper didn't clarify the position it places the non-local layer, I just have tried different places. I think that because I didn't put it behind the last Res block, there are still conv layer of the next stage behind the non-local layer I put.

**Comment by Woolseyyy** [comment]
Thank you for your reply!
