### ISSUE TITLE
DukeMTMC-videoreid dataset

### ISSUE THREAD

**Issue by ccq195** [jackie840129/STE-NVAN#8]
Dear author, 
thank you very much for the code you provided. Now I want to run the dukemtmc-videoreid dataset, but I find it impossible to download the dataset. Can you send me a copy of this dataset?Thank you very much。1013757040@qq.com

**Comment by jackie840129** [comment]
Maybe you can send an e-mail to the author of that dataset. I found that they remove the dataset because of some privacy issues.
